language: go

go:
  - 1.6

services:
  - docker

install:
  - go get github.com/Masterminds/glide

script:
  - make deps
  - make test

before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - make pushedge
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      - make push
    on:
      tags: true
